apiVersion: v1
kind: Secret
metadata:
  name: freepbx-secret
  namespace: freepbx
stringData:
  mysql-root-password: ENC[AES256_GCM,data:Hc4j8cOxPys=,iv:UdJaEd3+M/aOrgaJnXphRaqlgOayDsKj2z+8VuNChHY=,tag:zVXKkuKlG5FIHm4gHxv1gQ==,type:str]
  mysql-password: ENC[AES256_GCM,data:IV3ELo3bdweqBmK/,iv:+PBW9fkAnKpR7qkT+UtMseWNSiTdfLWhslUM7De3GT0=,tag:cuovimR8404q5h5qUY0Ouw==,type:str]
sops:
  age:
    - recipient: age1eljkxy6r497jeyanvczq9juqkj48dt38kevlenmdcsp8nud49sdqpfejwt
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2a0ZoNTdqbWpWeWZPUXls
        MUZBL0dpODBreTMvbDJBdDZKZE4rNklIcFhZClVabnBwUGQyQmxRMnhOMk5Saldl
        cEtPVHpXY0FScXVKQVFqQ2RzZVc0K1UKLS0tIE1VOElCSmg3RzBWV1NlQmx2NGxw
        UWxSRnpONkp5NENnWE9WaHBZNkpKb1UKkyo04sSmZGKZ2ahFklQgFSk9VSYRHQcZ
        qhEVtLflk2zGD7JcY781Rl4kUQpwkddYW6zwcb2UTK4n4FcYvY3oTw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-05-03T03:05:33Z"
  mac: ENC[AES256_GCM,data:Xs4zDydG5hAeIOGu4ra3Rad7MYOwNOKFHHdkMH4q+4HktnDRGsjtZbQXQDLcG+GhNmr9X1b07hG6+GehuyIgteFSLbGj2jvC4iMpI91E+cEnmBsP9KZdBA4oSfPidRzi4oH8UezQeD5e9SdPWvgJrlnstYzjim+AGJsIHzpSEM8=,iv:P6TJdmUjTuuN2BMGu4wKcZ93WuZq+VgCIO9kAy84Iyc=,tag:GpkS75//1AZ8t5y0YlzxWA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
