apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:Dx8kU/aRMH+H6gL0f3vuXv6ILqR9Pi+LsgFVRvppkYXGr5kuzptJHg==,iv:iZTfs9GOYZ+j0XkXwuUpdXMZ+V7So5CR4dxb8QoXWw0=,tag:UhU0O/ce2CSLPxIvP0qcpg==,type:str]
sops:
  age:
    - recipient: age1eljkxy6r497jeyanvczq9juqkj48dt38kevlenmdcsp8nud49sdqpfejwt
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5QXlaZC8xVTN3Y1hHRGdm
        aXZPT1VJNDdueTI5MVBVRWxZRzJmOSt0NWs4CmptM1lheUhiYlUrYW90a2JwWmF6
        cnRPTjhQMEdzbFZrMjZ2Z0M2WjZZN2MKLS0tIFNIY09mRjlySjlhNXJWelB2bEJx
        cm9ZR3RRc2wzNTdMYi9ISVVSZnlNcUkKQl2khSSwTG6J6Y8arL1ZP5LK1MAE+JLl
        SGkdg4gmfxBYioLmdwY5uoLNDIVsIhR0KjENSkMLfNd5Vl6UrIoLyQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-15T13:46:39Z"
  mac: ENC[AES256_GCM,data:AOONCacWVMa2haeMuIl1k3pqoHSzVJnKDsMMsInovOsYdTKaVXQKUs7+VpMQN9d1VsyZbC3QCF+PfzrhVh/GwV/c8lv1nrPrK5D5n3XvG6EsC8kPIF45jRRmfqLsjHGOVExC/4k2BbV9AmzzavyHFG6GWwx3heijHCSABc/1iaU=,iv:RbuA3MC44QGpBL5R4tqNvlYnzWUykNDhP97D9upoihs=,tag:CAbDeC80yfEo/r1ofyYsgg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
