apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:P+cWnLf6r5BNMuc/AsYJB1varraacLXRHkyKahAPFe9eBjhmNWZEHQ==,iv:9HYaHYrebEtCS9OZ6WXMI20RoOXqABWu5l8NLyD7tcc=,tag:0umAru4O244A9HNP6Ma1Bg==,type:str]
sops:
  age:
    - recipient: age1eljkxy6r497jeyanvczq9juqkj48dt38kevlenmdcsp8nud49sdqpfejwt
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6MmNNdFBBZ2ZSb05GSWFk
        Z1c2SWRLdXRFdGh3ZVErZGhMRGkrRklwSUZjCkhmemV5OE5iMXhqOEhIWXd0cEhs
        OTRLSUhESkMwc0tjVkpzVlJnaHFobXMKLS0tIE9vVVJTR25ocTRzWktud3Y2d0VQ
        empHTis1aXpzcTNFRk56VUpMM0tuWkUKHMhbTJxnplCd3388zpLEyBA+gswUkh0H
        5Kcklnb2sv6IAKNJxEen0ZY9pmE2lV5SPgRHr7TGOyyY5RdF+1zZIQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-15T07:17:41Z"
  mac: ENC[AES256_GCM,data:E55jgXlhiUSUalpvBVVSNuiTzBETHzHnd6nSjLKj1zhTJA2IdkKOciDeDYYuGxwaZY4jLMVynVLxdfkYDZV1OVFVPNvudJlEeyc6/nKHiIgg0kOpak2hH2X8kSvw28VJ1dwF6fdlghK6TJSIVqPn74OedmQtHSKhEsCjkkRFh70=,iv:+i6FoI8ScQXStJqZ8a2+6HmMFxImDVBLlJAkaDeLnu8=,tag:ydMEH8W2jKLoQ6ELQR5hZA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
