apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:9Ltyd8DAEiVhWNUBjOprfm4T8YLhpr3LTGlT+wMiwxUmxv2x2gzlgw==,iv:Q5/V21jJB7qPeRuJiVeyn0rnIox7/hoipY5sK/wK3jM=,tag:jbujv+kdyiFSbASH1eUdGg==,type:str]
sops:
  age:
    - recipient: age1eljkxy6r497jeyanvczq9juqkj48dt38kevlenmdcsp8nud49sdqpfejwt
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHYk1KU2U4VFhDZ25oNElL
        RWQya1BjWXBJQ3NTZERLYm9ZMURjU3oxaWg4CnB3Sjl6TWpjZUEvVXpHUmFNaUo0
        MG45TkJDdE85QVZtU1BIeFBMM0pmRUkKLS0tIGNNOE9ZVkwvRmdvdCtBZDNsV1dH
        dU9hblR1U0ZsVm5taEJsVWQveXo3RXMKdRAPicyFv07qLGAIjta6hkWJJrNQCJ+q
        8qdceHhNElYEDhb8zLLfdZ01aRvEhDRbp77MGLCVTwaSUcRtgrWDmw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-15T00:29:59Z"
  mac: ENC[AES256_GCM,data:G6wNbr2La30KeyyOUPJm3fkmdF8cYj3LCdijVD+jInYps4gVaDhnPgH7RTZOLznMcnkAWe+2IpvI+ngroc97uJQVL0Z4QfndwQi5S0ed3AFM034d83YjNaFv+7/9+tKR7Nqr1s75fObt7zDlLUXUGX1SqAnj1iSH7WLYelBn0w8=,iv:hladSFsGVmOGNRe8zCpI9RprTvBI8kMwNBnevxwm5fM=,tag:LDRXAm+nqjNMBwwYfPYZnw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
