apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:iKupxOdJ4UkpCvE=,iv:IwSHxcViXRoJdxpf4UykTlGIsqrwub6OH7a9qkrqS2A=,tag:BiRWhsUhy3HHuA0JOk1m6g==,type:str]
  NAS_SERVER: ENC[AES256_GCM,data:8NlPJ+0Vx4tV,iv:vmg1fE8I44GNnwNZwEtfyosWfJIkodBZZuBvBVsgh+E=,tag:jy9VCfVkY7wW7p620ZpkLA==,type:str]
  NAS_CODING_PATH: ENC[AES256_GCM,data:5/x6L8Kiv0GkluH8a5RA,iv:DXxp/XJB+E2/2XPXzWYzl94GkpHUGCUniNMQYWogSg0=,tag:qugUSkiMgZMz00cXdnmxiw==,type:str]
sops:
  age:
    - recipient: age1eljkxy6r497jeyanvczq9juqkj48dt38kevlenmdcsp8nud49sdqpfejwt
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZVi9PWDFvVkJWWnVaNCts
        Mm0xZnBGb0E5emNXQ09ITlVFeFVPZDFaY1NrCmdtZTIrcXZHWWRGb3IwajNDb2dO
        OWJaVlZFREJzVWZTUkpmdEs3dnorc2cKLS0tIEtPVmowNkFKeW80dGJFY3BUcnBZ
        TmE0TEFVOWZMK0V2Q05qN2lhUjZCNDgKbSKZ3q1ml91EGJqIBVg3QpnsA2KkOg46
        ZqWyck+tuf5av48qYPzsEglPAmGlu05ScPIOncziz3YNNzsLFY4VVA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-05-04T14:21:29Z"
  mac: ENC[AES256_GCM,data:j82HN/ZOeGy6YO3JaGdVtmicDRQHBYXz0jC2mu+tAjTnHSd2399JlvpYYfhsIEy/CRZOhrvKJng29f2vZhJF9ontqPZESBB7y/c5NnfJJtF2QAsDuudReTPqVWOuUBIrrMRfv7jy6nJYMvw/3XgPDcvskcnUAFvFIsOZDfVKyJI=,iv:BIsyRZcfvuSgdP1kT7ZGpMtU8Gsss6HFp6p7Ar3uTYc=,tag:94JibTv5RkDxk63/tGUy+A==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
