apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:OSG3SoEMDuQOKtU=,iv:NErUM+U4FYra+ES9W/EKIBdo36Amj1wBHmsQcTw3I+g=,tag:8aB6fsiJFi07Thbj6hR3fw==,type:str]
  NAS_SERVER: ENC[AES256_GCM,data:YFSqHQJLcVPH,iv:tjHROsF+LSEHFrk1ABUMYr3tehC2+bSg1lFM4r0eFQE=,tag:LGUdkjW/SH4AF4fIb7dz6g==,type:str]
  NAS_CODING_PATH: ENC[AES256_GCM,data:pss3M1Ft7C+jBef0Wag0,iv:A+Q7M9VV77lBD52DXknLBQyA81hA+tVaM62J84TrbSg=,tag:vgTtWjOrDGhYQGQnr++Jfg==,type:str]
  NAS_CLAUDE_USERS_PATH: ENC[AES256_GCM,data:U611r8nYnahMXcumlgl7wsLS3Rin,iv:Qrnl9Viz1gFbQRbDRaYiYGLx9ZGnpzs1sFkctK6A8Qk=,tag:ZZst69t73AxYkAe5LlnYYQ==,type:str]
sops:
  age:
    - recipient: age1eljkxy6r497jeyanvczq9juqkj48dt38kevlenmdcsp8nud49sdqpfejwt
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDNEFkUTZLSERYQmNBYmUx
        ZjFFYk1ma3UxTnUyeEJIeWhBZFE5ZFIrSmlFCnF2L0l1bDRDVk1GZ0N0dU05c0xP
        aytnNExGVXhkbkJvKzNKdThEQWc4aFEKLS0tIE1iNWhTektCT25yOE1CV2xhS0Fq
        U0ljOC9HdVVNdlNQcEhzTmR4NWU3LzAKqddLSr3yOWzqD3k3+lyNCu/6s33gDfef
        pDaekS9BYkSc+dAcUpCzq30iRocTVojhhm6hpI26Ry4RYQ86mTrutg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-05-05T07:19:33Z"
  mac: ENC[AES256_GCM,data:71UhQjX4C9ENXCqQqtF+ax5yM14axTuhGd4SRXwRtjatqLoiLa6MVgVj/+I4LM05KmKbWKyjF+UVLjI01oBJRTXGLgVO00JK1DlvHp2GK2OYee2cAxhOxx03OoyAU+YsuVZ9Je/FXNUneIYC44ZH9+c7ukCgPLyC7Wjpbyp//C4=,iv:19teilDQaJ3OzrU/q8MNtvAVq1VFRGQlXmUYVJ3iJqY=,tag:m+n3990L/nZzRjm3bYdFQA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
