apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:GQDwUsb6h3T0a3I75XedeXKB8j4kFjOfgkhjOjjT9yU=,iv:rFgid/wPWwoji6L0rvEMtizd26wJiStZlXJ3dVVCtYc=,tag:p384j5evC48g/vhqvu1M2A==,type:str]
sops:
  age:
    - recipient: age1eljkxy6r497jeyanvczq9juqkj48dt38kevlenmdcsp8nud49sdqpfejwt
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0RTRZZzlySzZuWjZ3U2RT
        dUs0bk01QXVRS0k3WnNXWTdmL3lSZ3NXK1JRCmpVRlo1QXBLRUJVVEVOMmNUb0oy
        QTdQMW91MEtqYThzWTRuVGhOeFVmbm8KLS0tIDZzeGJWNmJSOW5ZeTFGUjBkYjNy
        SE1SSzZNSysxMWpFc3g1WXlIelh2KzgKP2ZUs5pgnVSQ9z/yiETO5cjw2Mo2Okn1
        jN7zIYBwGK0Tp6SADZcaZJ1+5C/QBTH1eOB263PVq/9pZoszYTI42A==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-15T00:29:59Z"
  mac: ENC[AES256_GCM,data:ORYP0n2EwVASE71VV4oTR5BRXvDAIyQA5JdxvUxYVpvM7koFWJVD+4uAHvtDdZHYIEubpoiex1P+xKOjv4gVgT0mryF75fSmuxUrmSVgeJCTAEP1RViVa5lHF6ukIPH/AzzPYvNLQrso/I7+9xeTxzs1aGy9vL+hc/FUpwROV2I=,iv:wJPzb1DqgQ4VRhWbfu2dPlQgWNgkcWa+/hjSNP5cEGg=,tag:XZKxcXtl9fG2/gorg9UjEw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
