apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:TF6FVvNs1EeKWpOsptaFu9edLmx1EE83Qu6X8eo0lwk=,iv:zrDsD6s4V1ra1TobP0NyPnUjZFqBut7Xz7PJTAUPm+0=,tag:Au2RMjOF1WYXdmueCNvkmA==,type:str]
sops:
  age:
    - recipient: age1eljkxy6r497jeyanvczq9juqkj48dt38kevlenmdcsp8nud49sdqpfejwt
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyVFdpUVNYa29aVEpZejM0
        eW0vZGRkazE4TmpCeFdCdVVDcDFaQllvOGlNCk02VE5ZNEw5OWt1cktTcXI1ZlNj
        N2paOERkUHVjTUUxdUhvbUMzZldUSkUKLS0tIFZtTnlXMTNXeWxPSzlFckg3V3pY
        d1lHS0RPUUNkSlhqWDl2SlNFSXpIbzQKsiOXW7qW2GCWe9eJZnTEM8yiHNGVWJHR
        U6BmNduXJiDB8CUtl8rLjmhYRTvdRhSGbmYZRDRWiQUnTxadyBsknA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-15T07:17:41Z"
  mac: ENC[AES256_GCM,data:xH0SJMEfyf2cg1qZxc2+B/STtF+UA69noneV6Avb9izejiyWXftIHhFeYeiHeN3p1fl8ktCTdfqFwyk6SF+gLuZ+9GQXEwifsrX3ZIiI7ePowVZbaTjSU0wx5rSlS4n2VECW/GtQenGlmxvOFmbSM+UAWa791LdJVqce2852z9E=,iv:HbPWdk1x1CSADIFcB4lyM/wcGz/NgmfcaLVuhOuOJyE=,tag:kmtgDxRBwBG+d4RBPPmBFQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
