apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:RzYuD3KlgCMWjmAFLorJ8ovyJZvKvEMAzWcoKGfRTwE=,iv:5L52WuIINfHUarA4OAa8tokQNVp1DTyUd39OVw/yVRw=,tag:UklTpCil5CpDxPEfrnzWng==,type:str]
sops:
  age:
    - recipient: age1eljkxy6r497jeyanvczq9juqkj48dt38kevlenmdcsp8nud49sdqpfejwt
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3OExHWG1QMzhSY1UvWWFw
        SmExYWpJWXZnaUFqZkluUHJQMFEwUjl5MkM4CmdyUldsK1NHblNkR3dNMDNpNkZO
        SFJjd0U5OWZENmJVNmhiVU9uMTh1aG8KLS0tIGFZQzdMbi9Ud2trenZRY2dLQUYx
        TUJXcC9lMTVpck9jZisySmJOeEtuN1EKtLOi3mB2zH6wzo9YG6pagirTermEPot0
        qCsjBAIQTk2Zs3gxUFkllLGdbjhAHXWi2/AAuO6I6u0ZgZS9r5/eBQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-15T00:25:32Z"
  mac: ENC[AES256_GCM,data:o+O1whTTIFmrrx8kWWA1ybiCwYwi2Olosni96J8AX+ZP7LSYIgibse2GB9/KuSY4/N8IWNgphBOrNx4gXG9nsMyCisBqHGqBPgQDDKlcX0v3qX/Wbyu2ldPSXdh5dwiIE1vbZleqkQWbepYFZNJeHZe8k5gAeE9HsK+FAp6G7IA=,iv:TPvpQXGLJuXWWqtdfTYF2vp5uYMMZm0eZizbVjA7l+U=,tag:nlxprXGuthDYmQunCPp7Rg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
