apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:pRP/nkIHAPRrJMtaIGhEvsQuitQy1VsHhDaxkq+YzJMashqFb3SA0g78RkFDqHWggw6qtg/8OzkLbRzTteP0AIV8K6ruOWYMaJ1hWD+p7V7t5PDdHCJLHiKOkXkiYZvOEChu8tCnA5i+uORDE8RLU+TjF3bL0JdS7tthR1HC7fK184EPESd+sm+cBJr1tzOr8RutYMM8IdgA0uVs5OB4BNjTZgslY179Bs7PAzCsPMVu7f43,iv:cReTnyCOoI5a1dVCVZ72p34xRJhOtuyT1gSszRDS+fo=,tag:8SyANAASuc8WYFoyli0j+w==,type:str]
sops:
  age:
    - recipient: age1eljkxy6r497jeyanvczq9juqkj48dt38kevlenmdcsp8nud49sdqpfejwt
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBERXhRTTVvdG5QS3Z4OWF6
        STVPU3FhMXY1LzM0SjJpSkllSXh4UXJKMGtrClFVNVQvWmRGV2Nld0RhOFk4VGVt
        R3pzcDh1bEx1UUxPNmJUcktCMHltU0EKLS0tIGVORXFObXlsSkxYcEdGcGJDbGNj
        bmVLd0RqVm9lblF2ZE9ZbDdyZnAydmMKWj0NdBXVPM5wWqCRaSbJXVdBOE0JTdlg
        EBsVpursjERdzJj8dZjXT67JVdVRKuM/4yanKwixrd2tLa32+nCyHQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-15T00:29:59Z"
  mac: ENC[AES256_GCM,data:YhpCyD1/Ur9F8HnrnBPPCAwwznuMzRDXyPQ0Xqvll+Dtrr2b6ITmDdRSyYHl6Avd7eoZ1iCBDX1XF4bBrDxQA7NXNzZv2hZK7Svu2MeMvW1cG+BvHZzNFKInF62aNySWLh1fBNnu7unI3xyuqwietW/mRQ/rJ+M8IdlL546m3Ow=,iv:OC76K1Y7sNnYovg2UW3ddfUo5dW3bc/Sv44pCnkObJY=,tag:NO1Npc+WJboWItZb8EYdbw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
