apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:2sGkp4wY13xMjaGc8Rw45/mT+5VTw18zj3dce5HWPmrOJvaZsRhHuWRfDx3qY2V2ikX51DfSzJdmeuYHo3RGo2B8DnqozRHO/6nfS/AwqxacZCviHFjuBGJLKYF5CB3S9Hx5TzaQa2LhOJLjtfIOGjtWjA9KXNwKGBOC3ZeejpQWi6SdSyIQIgdfDAz2qe51cfqb9FjtM2yga5TbyKecIKGWpnjuhInGWoQ/FFUczptb+hEN,iv:CwYx76BZBr/bjL3k2ExLQO+ibovXefocUyLtzpF1du8=,tag:n7pREcIseiU/8b3vz6z8gA==,type:str]
sops:
  age:
    - recipient: age1eljkxy6r497jeyanvczq9juqkj48dt38kevlenmdcsp8nud49sdqpfejwt
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDRXptZFpkV25HT0dQMVZn
        N0tmUHQvSklscC9SUTBDMVNjSFA0eWo1SVU0CkUrRnpZU2dqMExmclM0NGF0VVFC
        eE5IV210YWRWcVAzNktGTkFqWndnMXcKLS0tIDlNdDRNWGlnOC9mVG93NzRDT3Vx
        NC9kOTNuZ0kvUWpCYmwwbjJ0SzBlSDgKid1HpmOr3fu4sIL+Fy19RbNWQKQHnOEL
        /FIfCZsAebQ0vkXQ1fXKjcubtz0blvPXBs5eDMfEkyjzg0nf/8n1Jg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-15T00:25:32Z"
  mac: ENC[AES256_GCM,data:z/CMaENbRFScSsc1NwuJX3IXBG64ebi3SIXkgjIlDrC2eSIrk0Xqm5EoO09yNOWb2AtGnhzpKNmTCLlJrc92Lelzz74hdJvasKKSBRbRQDeEAULjoqiDx9XZkbio5vooWrBPynvso9Xaxw0ltfjbtugGoTGPqDP87+/Cs/8swvM=,iv:hkRP53re6ZChw8GY1jquv+Nynu2ohfYSqMHuSAInDBw=,tag:D56WV55lSDuuJb8yVjT/4w==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
