apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:yZbU902tTMW2gf8GpJh87tzg0XYaCfht/6eO+hiygV45NFH5Go6LItCvryAdg6ne5pp7F+6bKUl1dkqCcaCo3iT44umHg25rIS5i62FNbEO/itiVebZ/HJcVVLQ/y08iCv0u95w1cPmRgJfZFN4jYd3rE31RODE7+Md9lRDWinaKl+Qt6yipy7D25tpeZ3aC9wzoOj61V75yTRKGIRQ3+XDH4Au2YmGGX8W84Lvegbzo/dYq,iv:13SDFwpF0Fp6Wr96Gl1yMwVoILWwSL3LtqMK+uMvdnA=,tag:9ajdiQfJDnehYejAs/kqPQ==,type:str]
sops:
  age:
    - recipient: age1eljkxy6r497jeyanvczq9juqkj48dt38kevlenmdcsp8nud49sdqpfejwt
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPWUFJcEpHU1R3aXkxMUo3
        bFdMTGpJYU1URlM1RDhHeStRcENzV0pWMDA4CmdMT0piZWdvRHJsU0xWQ1RQMUpp
        N1diRmFYZHZzSU1nTWJubENoZnl6Q1UKLS0tIGVxalFjMTg3cTRFV3VQVm9ROGhw
        TUNzaEtYWlhxUGIyZDlEWStIek9kbTQK6l9iN5Ow9X05mDP3xrOZ9tvt4HyvBVcu
        ulQpfVF9vqQQ6OXvu3ROOvRZ8QB1FMCuQIg/JiotnltuUab8LilCZA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-15T07:17:41Z"
  mac: ENC[AES256_GCM,data:DIx+8+cLtVmTvcE3AXNmd63jpX/6sFU7bwm4T5NIdIFj/MnbLlkrkpLDlk56+PW/zEehV3XiUp/nSL6PSc/eJdmlQf6wkJZdn+pPLox8321/fxzJ31WnC1g4ZmjDMFl6Ao6TvLld4tubF10YqVzpsQXYMH+URQegGNRWVDid0QI=,iv:nZroTJLKOhKF9637+ZfkZHf5goybgF6NTZblSJL/dNI=,tag:n4aEzVepaDzVo+S9JhX/xw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
