apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:xOzSypssYosIYqrNLqlVw9KuRrDH5IGdFAuN8SKEKHMXlubdcIVhqw==,iv:e84E4bccDV/rbAUYAjolIBKQXHz5//uipS+zm4Ui42U=,tag:lH7ZlvLVQOj7mPb9yCeSng==,type:str]
sops:
  age:
    - recipient: age1eljkxy6r497jeyanvczq9juqkj48dt38kevlenmdcsp8nud49sdqpfejwt
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1NmN5bzhjY2pvM0xka0Fa
        Tlh6YkI4eGNqUkUrNzdJRTNxdU9VL0g5TFI0CmFnZ1JzTFJNcXJjK0RXZzJLYWRa
        NlNyK0E0LzVoclFpREZnSDdqdHNQbkEKLS0tIElEWkFDY1dwSCtKRnhPWUlpWTUr
        czIwSFVkaW9EVHowRzhRbVU4RG5aYmMKxeb8Vjkb7A5VTXUEJF9WzmXSwGr2Yw9f
        sR0SVQc6XU3TvkJ0DBjTFW1DaS3oHHgoF9HBsBz3JdaO1ZhjxWXcLQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-15T00:25:32Z"
  mac: ENC[AES256_GCM,data:jIdZimcsNqXRBDupUwv8BS490EmRb5Xi1oRB062j5sO2bwNnRmY38Xb3nQ2PqgM3BCPshqm9FZs5iSAuxX02Xjhs61KkXuB3c+CB+kMqs9UeypjJVa1vssUHPwSqTcvqUFWrEEiGJjl1x8LdFVfuF6aNUQtX7DgLXVYdMO3LjV0=,iv:EjmPCNZ6N9joyukF6kCEr58lbjwSKtBe1TQ2f4YVlm0=,tag:Xh6/7U6EPUaizUkyXW6+zA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
