apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:4DSvKuE3d6ryC4QzUhJhFrxAjhkhQfwh7QgN2oqm3COuKD47dUzslg==,iv:tA7hJ1Wp34zQezGoAd9TMXlEFJh1eTqCkFIjIICrwoE=,tag:I5SWhzScgGLTQp580Jsv6Q==,type:str]
sops:
  age:
    - recipient: age1eljkxy6r497jeyanvczq9juqkj48dt38kevlenmdcsp8nud49sdqpfejwt
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhclNuZC8vcFA1Z2dvTDFr
        MkV0VXZyVFhWUnRjclY4K01Xd3VFSDRJZHljCjhEcjJ1dVBZZEY4UUptdGQ5eWtI
        ZElBZ2FXblJIT0E5RlVuZFNmaSsvbHcKLS0tIFBMVDU1eUl3cjhseWRlSjdBek1F
        NUxQOHp4SjMzd2sxOUo5L2lTZFNkeWsKOyEsn7witj4UX/ppUoMqTwPns2IKLne7
        37bb1rl0qMnpdEL6RVezI/tA1UKIX/IQk0AqljzutTblciKlpmW5/A==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-15T07:17:41Z"
  mac: ENC[AES256_GCM,data:1FY3wZs2lm9HSyb0DQHxsfgcev7KZpu0rvoWVbgsGBrgW1UpRgeDrTaJtjIYM4A8maalMvO5Tvop2d9EW6ETDf/vEAB7x1plaYt6QneQJnEt4F8PCY5i2w+0BFnYtr0PTpNFflSkhRxUwt9y+/jn+DtyUl7LIvSaejVvqp31LCg=,iv:+LmOCq7dmrV7BOQW7xFBHKlDO198xfmGX+4GRs7O60E=,tag:PhlVB8Vfa3ZdbFLVN2XNIA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
