apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:6zxfqNo0IKz0vzWgiCTUAB4CdJiOjPG0wd4ZI51LXoDg1gLd1yFcGA==,iv:Lv3zMV4B9Tc3Wk8WHfIg7OHqazVhju3StoEFW14x2uM=,tag:qdRdYRMTnW62xfHsuforZA==,type:str]
sops:
  age:
    - recipient: age1eljkxy6r497jeyanvczq9juqkj48dt38kevlenmdcsp8nud49sdqpfejwt
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArc1JlbUYzU25QdkgzdGs3
        ZSs5Y25MMDFGWjlhUkh3UGVBVjA2V3NDVDN3CmlCOHVHT0VoQWNyVVZZa0lVSEdB
        bFRLdjhyM0lmbnlnN0k4MUkrTjJpdFEKLS0tIE9wRUJRdnpLSGJiN093UjR1RTNB
        SUsxdHIySVRFbWJtK3U3Q0szK1NHeTAKoa3XL4Diw4pH8568pqLyMzLNsQnH1ZM+
        HcyrhTMxGkUNCjuUJM2cP5iEEPfyHNtGWuNl9tKD2KKNFAba6LpnJg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-15T13:46:39Z"
  mac: ENC[AES256_GCM,data:LpC4nPHO3mFLCys0xdZ/m6G2y0jkMH1Le+YLjhKX9PvyF58tb3TYonJx/gck8XGuXuucJc6c5ZKVCTj/i9oxV0YKVH+r3vN/RH5nMtf/Hi6eQrPqrOnTnc4uuI6bCN6y1pH3Z/pcoymZfjxEvH/t0RcB7mLHx2WnHYTpoX+b5Mk=,iv:Eygiy1mZtO+TNXMns+8PQKUxjR9tq1kVnh+JlQeF1yE=,tag:X1YF1UXgpCdy3YcdTAxFRg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
